### ISSUE TITLE
Can not transfer SUB successfully: Bad Origin

### ISSUE THREAD

**Issue by Wangmmx** [dappforce/subsocial-node#126]
I submit SUB transaction to the node, it has no error, but When I search it on chain , found it failed `DispatchError  BadOrigin`, is SUB can transfer now? Or is there something wrong with my transaction body? How can I solve it? thanks a lot

**Comment by F3Joule** [comment]
Hello. Thank you for your query.

Currently SUB token is utility token, which is described in our [Tokens Disclamer](https://app.subsocial.network/legal/token). You really cannot transfer them yet.
