### ISSUE TITLE
can not sync block at 6600871

### ISSUE THREAD

**Issue by atenjin** [dappforce/subsocial-node#160]
no other detail log for info level, just like following:
```bash
Nov 13 22:12:22 node3-SG subsocial-node[193229]: 2021-11-13 22:12:22.486   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.1kiB/s ⬆ 1.2kiB/s
Nov 13 22:12:27 node3-SG subsocial-node[193229]: 2021-11-13 22:12:27.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.2kiB/s ⬆ 1.2kiB/s
Nov 13 22:12:32 node3-SG subsocial-node[193229]: 2021-11-13 22:12:32.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.8kiB/s ⬆ 2.1kiB/s
Nov 13 22:12:37 node3-SG subsocial-node[193229]: 2021-11-13 22:12:37.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 2.9kiB/s ⬆ 1.5kiB/s
Nov 13 22:12:42 node3-SG subsocial-node[193229]: 2021-11-13 22:12:42.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.5kiB/s ⬆ 1.8kiB/s
Nov 13 22:12:47 node3-SG subsocial-node[193229]: 2021-11-13 22:12:47.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.1kiB/s ⬆ 1.8kiB/s
Nov 13 22:12:52 node3-SG subsocial-node[193229]: 2021-11-13 22:12:52.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.6kiB/s ⬆ 1.7kiB/s
Nov 13 22:12:57 node3-SG subsocial-node[193229]: 2021-11-13 22:12:57.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.3kiB/s ⬆ 1.5kiB/s
Nov 13 22:13:02 node3-SG subsocial-node[193229]: 2021-11-13 22:13:02.486   INFO tokio-runtime-worker substrate: ⚙️  Syncing  0.0 bps, target=#6611542 (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.0kiB/s ⬆ 1.2kiB/s
Nov 13 22:13:07 node3-SG subsocial-node[193229]: 2021-11-13 22:13:07.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 4.2kiB/s ⬆ 53.4kiB/s
Nov 13 22:13:12 node3-SG subsocial-node[193229]: 2021-11-13 22:13:12.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 57.8kiB/s ⬆ 52.6kiB/s
Nov 13 22:13:17 node3-SG subsocial-node[193229]: 2021-11-13 22:13:17.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 59.4kiB/s ⬆ 53.1kiB/s
Nov 13 22:13:22 node3-SG subsocial-node[193229]: 2021-11-13 22:13:22.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 60.1kiB/s ⬆ 22.0kiB/s
Nov 13 22:13:27 node3-SG subsocial-node[193229]: 2021-11-13 22:13:27.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.7kiB/s ⬆ 2.0kiB/s
Nov 13 22:13:32 node3-SG subsocial-node[193229]: 2021-11-13 22:13:32.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 0.8kiB/s ⬆ 1.1kiB/s
Nov 13 22:13:37 node3-SG subsocial-node[193229]: 2021-11-13 22:13:37.487   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 3.1kiB/s ⬆ 2.5kiB/s
Nov 13 22:13:42 node3-SG subsocial-node[193229]: 2021-11-13 22:13:42.487   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 0.8kiB/s ⬆ 176.0kiB/s
Nov 13 22:13:47 node3-SG subsocial-node[193229]: 2021-11-13 22:13:47.487   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 2.0kiB/s ⬆ 2.1kiB/s
```

node version: subsocial-node 0.7.0-5c62197-x86_64-linux-gnu

**Comment by F3Joule** [comment]
You have to upgrade to `0.7.1`.
It's available here: https://github.com/dappforce/subsocial-node/tree/develop-polkadot-v0.9.10

**Comment by COLUD4** [comment]
![截屏2022-01-12 下午4 23 54](https://user-images.githubusercontent.com/21240219/149134730-dfa681e2-3c63-473f-9151-1feff25b6441.png)

Node starts but connects 0 peers

**Comment by COLUD4** [comment]
> no other detail log for info level, just like following:
> 
> ```shell
> Nov 13 22:12:22 node3-SG subsocial-node[193229]: 2021-11-13 22:12:22.486   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.1kiB/s ⬆ 1.2kiB/s
> Nov 13 22:12:27 node3-SG subsocial-node[193229]: 2021-11-13 22:12:27.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.2kiB/s ⬆ 1.2kiB/s
> Nov 13 22:12:32 node3-SG subsocial-node[193229]: 2021-11-13 22:12:32.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.8kiB/s ⬆ 2.1kiB/s
> Nov 13 22:12:37 node3-SG subsocial-node[193229]: 2021-11-13 22:12:37.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 2.9kiB/s ⬆ 1.5kiB/s
> Nov 13 22:12:42 node3-SG subsocial-node[193229]: 2021-11-13 22:12:42.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.5kiB/s ⬆ 1.8kiB/s
> Nov 13 22:12:47 node3-SG subsocial-node[193229]: 2021-11-13 22:12:47.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.1kiB/s ⬆ 1.8kiB/s
> Nov 13 22:12:52 node3-SG subsocial-node[193229]: 2021-11-13 22:12:52.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.6kiB/s ⬆ 1.7kiB/s
> Nov 13 22:12:57 node3-SG subsocial-node[193229]: 2021-11-13 22:12:57.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.3kiB/s ⬆ 1.5kiB/s
> Nov 13 22:13:02 node3-SG subsocial-node[193229]: 2021-11-13 22:13:02.486   INFO tokio-runtime-worker substrate: ⚙️  Syncing  0.0 bps, target=#6611542 (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.0kiB/s ⬆ 1.2kiB/s
> Nov 13 22:13:07 node3-SG subsocial-node[193229]: 2021-11-13 22:13:07.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 4.2kiB/s ⬆ 53.4kiB/s
> Nov 13 22:13:12 node3-SG subsocial-node[193229]: 2021-11-13 22:13:12.486   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 57.8kiB/s ⬆ 52.6kiB/s
> Nov 13 22:13:17 node3-SG subsocial-node[193229]: 2021-11-13 22:13:17.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 59.4kiB/s ⬆ 53.1kiB/s
> Nov 13 22:13:22 node3-SG subsocial-node[193229]: 2021-11-13 22:13:22.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 60.1kiB/s ⬆ 22.0kiB/s
> Nov 13 22:13:27 node3-SG subsocial-node[193229]: 2021-11-13 22:13:27.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 1.7kiB/s ⬆ 2.0kiB/s
> Nov 13 22:13:32 node3-SG subsocial-node[193229]: 2021-11-13 22:13:32.487   INFO tokio-runtime-worker substrate: 💤 Idle (3 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 0.8kiB/s ⬆ 1.1kiB/s
> Nov 13 22:13:37 node3-SG subsocial-node[193229]: 2021-11-13 22:13:37.487   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 3.1kiB/s ⬆ 2.5kiB/s
> Nov 13 22:13:42 node3-SG subsocial-node[193229]: 2021-11-13 22:13:42.487   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 0.8kiB/s ⬆ 176.0kiB/s
> Nov 13 22:13:47 node3-SG subsocial-node[193229]: 2021-11-13 22:13:47.487   INFO tokio-runtime-worker substrate: 💤 Idle (4 peers), best: #6600871 (0xaa1c…f582), finalized #6600871 (0xaa1c…f582), ⬇ 2.0kiB/s ⬆ 2.1kiB/s
> ```
> 
> node version: subsocial-node 0.7.0-5c62197-x86_64-linux-gnu

Hello! The node I built is started, but the connection is 0 peers. How did you synchronize the nodes? Thank you so much!
