### ISSUE TITLE
Error when build code

### ISSUE THREAD

**Issue by maxbitov** [dappforce/subsocial-node#61]
after launch 
cargo build --release
appear the error:

 Compiling frame-support v2.0.0-rc4 (https://github.com/paritytech/substrate.git?tag=v2.0.0-rc4#00768a1f)
  error[E0424]: expected value, found module `self`
      --> /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/00768a1/frame/support/src/traits.rs:1172:11
       |
  1170 | / bitmask! {
  1171 | |     /// Reasons for moving funds out of an account.
  1172 | |     #[derive(Encode, Decode)]
       | |              ^^^^^^ `self` value is a keyword only available in methods with a `self` parameter
  1173 | |     pub mask WithdrawReasons: i8 where
  ...    |
  1188 | |     }
  1189 | | }
       | |_- this function has a `self` parameter, but a macro invocation can only access identifiers it receives from parameters
       |
       = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0424`.
  error: could not compile `frame-support`.

**Comment by F3Joule** [comment]
This is a bug related to Substrate w/ Rust compatibility. Since we use Substrate v2.0.0-rc4, this bug isn't fixed yet.
The working fix is:
```
rustup install nightly-2020-07-12
ustup target add wasm32-unknown-unknown --toolchain nightly-2020-07-12
rustup override set nightly-2020-07-12
```

**Comment by F3Joule** [comment]
Correct rust toolchains since #108 will be specified in the [init.sh](../scripts/init.sh) file.

**Comment by siman** [comment]
Should be fixed by this PR: https://github.com/dappforce/subsocial-node/pull/108
