### ISSUE TITLE
add rust version info for build

### ISSUE THREAD

**Issue by bingryan** [dappforce/subsocial-node#85]
hi, 
Initialize Wasm Build environment
```
./scripts/init.sh
```
then build

```
cargo build --release
```
will get error 

add specified version at `rust-toolchain` file  maybe  a good choice.

I solve the compilation problem by specifying the version.
```
rustup install nightly-2020-06-27
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-06-27
```
then build

```
cargo build --release
```

**Comment by F3Joule** [comment]
#61

**Comment by siman** [comment]
Should be fixed by this PR: https://github.com/dappforce/subsocial-node/pull/108
